### ISSUE TITLE
How to compile

### ISSUE THREAD

**Issue by miathedev** [cnlohr/spreadgine#4]
Actually,

how did you compile the source code?
This project is awesome. I saw it on youtube.

It seems i picked the worng linmath.h. Thats why im asking.

**Comment by cnlohr** [comment]
Hmmm... This project has been largely superceded. What application are you thinking about using it for?  It's specifically for using on an rpi and forwarding the draw calls. You should be able to just type make

**Comment by miathedev** [comment]
I really forgot for what i wanted to use spreadgine. Im not sure - but i think i wanted to use it for some VR experiments.
Sounds idiotic, but i cant remember. Im really really sorry.

Somehow i wasnt notified via Mail. Im closing this issue.
